In [42]:
import torch
import numpy as np

In [43]:
# initialize a tensor from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
# initialize a tensor from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# initialize a tensor with random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
# initialize a tensor from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data

# print the tensors
print(f"Data Tensor: \n{x_data} \n")
print(f"From numpy array: \n{x_np} \n")
print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor} \n")
print(f"Ones like x_data: \n{x_ones} \n")
print(f"Random like x_data: \n{x_rand} \n")


Data Tensor: 
tensor([[1, 2],
        [3, 4]]) 

From numpy array: 
tensor([[1, 2],
        [3, 4]]) 

Random Tensor: 
tensor([[0.0137, 0.5346, 0.9524],
        [0.5244, 0.2238, 0.3034]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Ones like x_data: 
tensor([[1, 1],
        [1, 1]]) 

Random like x_data: 
tensor([[0.4354, 0.2588],
        [0.2982, 0.3262]]) 



In [44]:
# Attributes of a Tensor
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [45]:
# Operations on tensors
# Move the tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Device tensor is stored on: {tensor.device} \n")

# Standard numpy-like indexing and slicing
tensor = torch.tensor([[1., 2., 3.], [1.,2.,3.], [1.,2.,3.]])
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]} \n")
tensor[:,1] = 0
print(tensor)
print('\n')

Device tensor is stored on: cpu 

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])
First row: tensor([1., 2., 3.])
First column: tensor([1., 1., 1.])
Last column: tensor([3., 3., 3.]) 

tensor([[1., 0., 3.],
        [1., 0., 3.],
        [1., 0., 3.]])




In [46]:
# Joining tensors
t1 = torch.cat([tensor, tensor], dim=0) # along existing dimension
print(f"Joining along existing dimension: \n {t1} \n")
t2 = torch.stack([tensor, tensor], dim=0) # creates a new dimension
print(f"Joining along a new dimension:\n {t2}")

Joining along existing dimension: 
 tensor([[1., 0., 3.],
        [1., 0., 3.],
        [1., 0., 3.],
        [1., 0., 3.],
        [1., 0., 3.],
        [1., 0., 3.]]) 

Joining along a new dimension:
 tensor([[[1., 0., 3.],
         [1., 0., 3.],
         [1., 0., 3.]],

        [[1., 0., 3.],
         [1., 0., 3.],
         [1., 0., 3.]]])


In [47]:
# Arithmetic operations
# Matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f"y1 = {y1} \ny2 = {y2} \ny3 = {y3}")

y1 = tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]) 
y2 = tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]) 
y3 = tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


In [48]:
# Element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z1 = {z1} \nz2 = {z2} \nz3 = {z3}")


z1 = tensor([[1., 0., 9.],
        [1., 0., 9.],
        [1., 0., 9.]]) 
z2 = tensor([[1., 0., 9.],
        [1., 0., 9.],
        [1., 0., 9.]]) 
z3 = tensor([[1., 0., 9.],
        [1., 0., 9.],
        [1., 0., 9.]])


In [49]:
# Bridge with NumPy
# Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}\n")

# A change in the tensor reflects in the NumPy array
t.add_(1)   # in-place addition
print(f"t: {t}")
print(f"n: {n}\n")

# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

# Changes in the NumPy array reflects in the tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
